# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_auto_20160830_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
