# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_auto_20160902_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='image_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
