# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_auto_20160903_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='background_color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
