# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_auto_20160905_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image_url',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
