# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 02:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_auto_20160905_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
            preserve_default=False,
        ),
    ]
