# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_auto_20160919_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post',
            field=models.TextField(default='Test post, please ignore'),
            preserve_default=False,
        ),
    ]
